SELECT DISTINCT
(ID.EXPEDIENTE),
EM.ESTADO ID_ENTIDAD,
CENT.CDESENTFED ENTIDAD,
EM.MUNICIPIO ID_MUNICIPIO,
CMUN.DESCRIP MUNICIPIO,
REPLACE(REPLACE(REPLACE(REPLACE(N.DNOMBRE,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  NOMBRE,
REPLACE(REPLACE(REPLACE(REPLACE(N.DPATERNO,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  PATERNO,
REPLACE(REPLACE(REPLACE(REPLACE(N.DMATERNO,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  MATERNO,
ID.codbar cib,
          CASE
             WHEN iD.sexo IN ('1', 'M', '9') THEN 'MASCULINO'
             WHEN iD.sexo IN ('2', 'F', 'D') THEN 'FEMENINO'
             ELSE 'SIN INFORMACION'
          END
             sexo,
ID.ESTATURA,
ID.PESO,
REPLACE(REPLACE(REPLACE(REPLACE(cd.descrip,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  delito,
          CASE
             WHEN clasifica = 'I' THEN 'INDICIADO'
             WHEN clasifica = 'P' THEN 'PROCESADO'
             WHEN clasifica = 'S' THEN 'SENTENCIADO'
             WHEN clasifica = 'C' THEN 'COMPURGADO'
             WHEN clasifica = 'U' THEN 'IDENTIFICADO'
             WHEN clasifica = 'L' THEN 'LIBERADO'
             WHEN clasifica = 'R' THEN 'PRELIBERADO'
             WHEN clasifica = 'B' THEN 'EVADIDO'
          END
             CLASIFICACION_JURIDICA,
          CASE
             WHEN SIT.FUERO = 'C' THEN 'COMUN'
             WHEN SIT.FUERO = 'F' THEN 'FEDERAL'
             WHEN SIT.FUERO = 'M' THEN 'MILITAR'
             ELSE 'SIN CLASIFICAR'
          END
             AS FUERO,  
  REPLACE(REPLACE(REPLACE(REPLACE(SIT.PROCESO,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  PROCESO,
--replace(replace( JUR.NJUZGADO,chr(13)||chr(10), ' '), chr(9), ' ') NOMBRE_JUZGADO,
REPLACE(REPLACE(REPLACE(REPLACE(JUR.NJUZGADO,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  NOMBRE_JUZGADO,
            CASE
             WHEN IDC.ESTEXP = '1' THEN 'ACTIVO'
           --  WHEN IDC.ESTEXP = '2' THEN 'HISTORICO'
             ELSE 'SIN CLASIFICAR'
          END
             AS ESTADO_EXPEDIENTE,
  REPLACE(REPLACE(REPLACE(REPLACE(EM.EMISOR,CHR(9),''),CHR(10),''),CHR(13),''),'"', '') EMISOR,
  CEM.DESCRIP EMISOR_1,
  trunc(EM.FECHA_REGISTRO) FECHA_REGISTRO_EMISOR,
  TRUNC(EM.FECHA_ACTUALIZACION) FECHA_ACTUALIACION_EMISOR,
  TRUNC(EJ.FECHINGCENT) FECHA_INGRESO_EJECUCION,  ------------------------------------------                              
  EJ.PENAANO PENA_EN_ANIOS,                                    
  EJ.PENAMES PENA_EN_MESES,                                    
  EJ.PENADIA PENA_EN_DIAS,
  CASE
    WHEN IMF.IMAKEY IS NOT NULL THEN '1'
    ELSE '0'
   END
     FOTO_FRENTE,
  TRUNC(ID.FECHA_CAP) AS  FECHA_CAPTURA,
  CASE
  WHEN JUR.CALIDAD = 'P' THEN 'PRIMO DELINCUENTE'
  WHEN JUR.CALIDAD = 'M' THEN 'MULTIREINCIDENTE'
  WHEN JUR.CALIDAD = 'R' THEN 'REINCIDENTE'
  ELSE 'SIN CLASIFICAR'
  END
    AS CALIDAD_DELINCUENCIAL,
  CASE
      WHEN SIT.PELIGRO = 'A' THEN 'ALTA'
      WHEN SIT.PELIGRO = 'M' THEN 'MEDIA'
      WHEN SIT.PELIGRO = 'B' THEN 'BAJA'
  ELSE 'SIN CLASIFICAR'
  END
    AS PELIGROSIDAD,
   REPLACE(REPLACE(REPLACE(REPLACE(CP.NACIONA,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  NACIONALIDAD,  
ID.FEC_NAC FECHA_NACIMIENTO,
ID.RFC,
ID.EDAD,
    REPLACE(REPLACE(REPLACE(REPLACE(CEC.DESCRIP,CHR(9),''),CHR(10),''),CHR(13),''),'"', '') ESTADO_CIVIL,
           CASE
             WHEN ID.TIPOEXP = 1 THEN 'FEDERAL'
             WHEN ID.TIPOEXP = 2 THEN 'COMUN'
             WHEN ID.TIPOEXP = 3 THEN 'FEDERAL-COMUN'
             ELSE 'SIN DATO'
          END
             TIPO_EXPEDIENTE,
          CASE
             WHEN IDC.UBICACIONIND = '1' THEN 'INTERNO'
             WHEN IDC.UBICACIONIND = '2' THEN 'DETENIDO'
             WHEN IDC.UBICACIONIND = '3' THEN 'EN LIBERTAD'
             WHEN IDC.UBICACIONIND = '4' THEN 'DIFUNTO'
             ELSE 'SIN DATO'
          END
             AS UBICACION_INDIVIDUO,
CENT.CDESENTFED ENTIDAD_DOM,
CMUN.DESCRIP MUNICIPIO_DOM,
replace(replace(DOM.DCOLONIA,chr(13)||chr(10), ' '), chr(9), ' ')  COLONIA,
replace(replace(DOM.DCALLE,chr(13)||chr(10), ' '), chr(9), ' ')  CALLE,                                                
DOM.DCP CP_DOM,  
    REPLACE(REPLACE(REPLACE(REPLACE(CMO.ID_DESMOD,CHR(9),''),CHR(10),''),CHR(13),''),'"', '')  MODALIDAD,
TRUNC(EXT.FEXTERNA) FECHA_EXTERNACION,
 
  NVL2(VEM.EXPEDIENTE, 1, 0) AS MARCAS,
 
  NVL2(VEM.EXPEDIENTE,1,0 )AS CICATRICES,
 
  NVL2(VET.EXPEDIENTE,1,0) AS TATUAJES,
 
  NVL2(VEL.EXPEDIENTE,1,0) AS LUNARES,
 
  NVL2(V.VOZKEY,1,0) AS VOZ,
 
  NVL2(VEFD.EXPEDIENTE,1,0) AS FOTO_PDER,
  NVL2(VEFI.EXPEDIENTE,1,0) AS FOTO_PIZQ,
  CASE
    WHEN SIT.PELIGRO = 'A' THEN 'ALTA'
    WHEN SIT.PELIGRO = 'M' THEN 'MEDIA'
    WHEN SIT.PELIGRO = 'B' THEN 'BAJA'
    ELSE 'SIN CLASIFICAR'
END
   AS PELIGRO,  
REPLACE(REPLACE(REPLACE(REPLACE(A.ALIAS,CHR(9),''),CHR(10),''),CHR(13),''),'"', '') ALIAS
--SELECT A.*
FROM RIPSADM.EMISORES EM
LEFT JOIN RIPSADM.IDENTIFICACION ID ON ID.EXPEDIENTE=EM.EXPEDIENTE
-----------------------
LEFT JOIN RIPSADM.V_EXISTE_MARCA    VEM     ON VEM.EXPEDIENTE = EM.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_CICATRIZ VEC     ON VEC.EXPEDIENTE = EM.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_TATUAJE  VET     ON VET.EXPEDIENTE = EM.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_LUNAR    VEL        ON VEL.EXPEDIENTE = EM.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_FOTO_PDER VEFD     ON VEFD.EXPEDIENTE = EM.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_FOTO_PIZQ VEFI    ON VEFI.EXPEDIENTE = EM.EXPEDIENTE
----------------------
LEFT JOIN RIPSADM.DOMICILIO DOM   ON DOM.EXPEDIENTE=ID.EXPEDIENTE
LEFT JOIN RIPSADM.C_ENTIDADES CENT ON CENT.NCVEENTFED=EM.ESTADO  
LEFT JOIN RIPSADM.CAT_MUNICI  CMUN ON CMUN.LLAVE_M=EM.MUNICIPIO AND CMUN.LLAVE_E=CENT.NCVEENTFED
LEFT JOIN RIPSADM.NOMBRES N ON N.EXPEDIENTE=EM.EXPEDIENTE AND N.ID_NOMBRE=1
LEFT JOIN RIPSADM.EXTERNACION EXT ON EXT.EXPEDIENTE=EM.EXPEDIENTE
LEFT JOIN RIPSADM.SITUACION SIT   ON SIT.EXPEDIENTE=EM.EXPEDIENTE
LEFT JOIN RIPSADM.JURIDICOS  JUR  ON JUR.EXPEDIENTE=EM.EXPEDIENTE
LEFT JOIN RIPSADM.ODELITO OD      ON OD.EXPEDIENTE=EM.EXPEDIENTE
LEFT JOIN RIPSADM.cat_delitos cd  ON OD.delito = cd.llave
LEFT JOIN RIPSADM.CAT_MODALI CMO ON OD.DELITO = CMO.ID_DELITO AND OD.MODALIDAD = CMO.ID_MODALIDAD
LEFT JOIN RIPSADM.IDENCOMP IDC ON Em.EXPEDIENTE = IDC.EXPEDIENTE
LEFT JOIN RIPSADM.CAT_EMISOR CEM  ON CEM.LLAVE=EM.EMISOR
LEFT JOIN RIPSADM.EJECUCION EJ ON EM.EXPEDIENTE = EJ.EXPEDIENTE
LEFT JOIN RIPSADM.V_EXISTE_IMAGEN IMF ON EM.EXPEDIENTE = IMF.EXPEDIENTE
LEFT JOIN RIPSADM.CAT_PAISES CP ON ID.NNACIONA = CP.LLAVE
LEFT JOIN RIPSADM.CAT_EDOCIVIL CEC ON ID.EST_CIV = CEC.LLAVE
LEFT JOIN RIPSADM.VOZ V ON EM.EXPEDIENTE = V.EXPEDIENTE
LEFT JOIN RIPSADM.ALIAS A ON EM.EXPEDIENTE = A.EXPEDIENTE
WHERE IDC.ESTEXP = 1;
